development: &default
  adapter: postgresql
  encoding: unicode
  database: primehacker_development
  username: postgres
  pool: 5
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: primehacker_test
  min_messages: warning
